name: Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  unit:
    strategy:
      matrix:
        php-version: ['8.0', '7.4', '5.6']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Validate composer.json
        run: composer validate --strict

      - run: composer install

      - run: composer run phpunit

  behat:
    strategy:
      matrix:
        php-version: ['8.0', '7.4', '5.6']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Setup MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE wp_cli_test;' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1";' -uroot -proot

      - run: composer install

      - run: composer run behat


